### PR TITLE
decommission the adorable rorable

### PR DESCRIPTION
**Pull request by edquist**
i loved it but i think it was a bit much for people to get cozy with.

### CODE REVIEW

**Review by matyasselmeci — APPROVED** [review]
LGTM. Sorry :)

**Comment by matyasselmeci** [comment]
The CI failed due to the Python version missing in the GHA. @brianhlin might remember better but I think we solved it elsewhere by setting the version explicitly to "3.6.15" instead of just "3.6".

**Comment by brianhlin** [comment]
> I think we solved it elsewhere by setting the version explicitly to "3.6.15" instead of just "3.6".

Exactly right

**Comment by edquist** [comment]
I updated but still getting this:

```
Version 3.6.15 was not found in the local cache
Error: Version 3.6.15 with arch x64 not found
The list of all available versions can be found here:
https://raw.githubusercontent.com/actions/python-versions/main/versions-manifest.json
```

But 3.6.15 was in the list, but only up through ubuntu 20.04, so i made that explicit also.  CI passes now.

**Pull request merged**
